import { useEffect, useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { apiRequest } from "../../services/api";

export default function ParentDashboard() {
  const { user, logout } = useAuth();
  const parentId = user?.id;

  const [activeTab, setActiveTab] = useState("overview");
  const [child, setChild]           = useState(null);
  const [attendance, setAttendance] = useState([]);
  const [marks, setMarks]           = useState([]);
  const [feedbacks, setFeedbacks]   = useState([]);
  const [meetings, setMeetings]     = useState([]);
  const [teachers, setTeachers]     = useState([]);

  useEffect(() => {
    if (!parentId) return;
    // CORRECT ✅
apiRequest(`/parent/${parentId}/child`).then(setChild).catch(console.error);
apiRequest(`/parent/${parentId}/attendance`).then(setAttendance).catch(console.error);
apiRequest(`/parent/${parentId}/marks`).then(setMarks).catch(console.error);
apiRequest(`/parent/${parentId}/feedback`).then(setFeedbacks).catch(console.error);
apiRequest(`/parent/${parentId}/meetings`).then(setMeetings).catch(console.error);
apiRequest(`/parent/${parentId}/teachers`).then(setTeachers).catch(console.error);
  }, [parentId]);

  // ── Computed stats ──────────────────────────────────────────────────────────
  const totalDays     = attendance.length;
  const presentDays   = attendance.filter(a => a.status === "Present").length;
  const attendancePct = totalDays > 0 ? Math.round((presentDays / totalDays) * 100) : 0;
  const avgMarks      = marks.length > 0
    ? Math.round(marks.reduce((sum, m) => sum + (m.marks / m.max_marks) * 100, 0) / marks.length)
    : 0;
  const upcomingMeetings = meetings.filter(m => m.status === "Scheduled").length;

  // ── PDF Download ────────────────────────────────────────────────────────────
  const downloadReport = () => {
    const printContent = `
      <html>
      <head>
        <title>Student Report - ${child?.student_name}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 30px; color: #333; }
          h1 { color: #1a56db; }
          h2 { color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-top: 30px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th { background: #f3f4f6; text-align: left; padding: 8px 12px; font-size: 13px; }
          td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
          .badge { padding: 3px 8px; border-radius: 20px; font-size: 12px; }
          .present { background: #dcfce7; color: #16a34a; }
          .absent  { background: #fee2e2; color: #dc2626; }
          .info    { background: #f9fafb; border-radius: 8px; padding: 15px; margin-top: 10px; }
          .info p  { margin: 4px 0; font-size: 13px; }
          .footer  { margin-top: 40px; font-size: 12px; color: #9ca3af; text-align: center; }
        </style>
      </head>
      <body>
        <h1>🎓 Mentra — Student Report</h1>
        <div class="info">
          <p><strong>Name:</strong> ${child?.student_name}</p>
          <p><strong>Roll No:</strong> ${child?.roll_no}</p>
          <p><strong>Class:</strong> ${child?.class} - ${child?.section}</p>
          <p><strong>Attendance:</strong> ${attendancePct}% (${presentDays}/${totalDays} days)</p>
          <p><strong>Average Marks:</strong> ${avgMarks}%</p>
        </div>

        <h2>📊 Marks</h2>
        <table>
          <thead>
            <tr>
              <th>Subject</th>
              <th>Exam Type</th>
              <th>Marks</th>
              <th>Max</th>
              <th>Percentage</th>
            </tr>
          </thead>
          <tbody>
            ${marks.map(m => `
              <tr>
                <td>${m.subject}</td>
                <td>${m.exam_type}</td>
                <td>${m.marks}</td>
                <td>${m.max_marks}</td>
                <td>${((m.marks / m.max_marks) * 100).toFixed(1)}%</td>
              </tr>
            `).join("")}
          </tbody>
        </table>

        <h2>📅 Attendance Record</h2>
        <table>
          <thead>
            <tr><th>Date</th><th>Status</th></tr>
          </thead>
          <tbody>
            ${attendance.map(a => `
              <tr>
                <td>${a.date}</td>
                <td><span class="badge ${a.status === 'Present' ? 'present' : 'absent'}">${a.status}</span></td>
              </tr>
            `).join("")}
          </tbody>
        </table>

        <div class="footer">
          Generated by Mentra on ${new Date().toLocaleDateString()}
        </div>
      </body>
      </html>
    `;

    const printWindow = window.open("", "_blank");
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  return (
    <div className="bg-secondary min-h-screen">

      {/* Header */}
      <div className="bg-white border-b px-10 py-4 flex justify-between items-center">
        <div className="flex items-center gap-3">
          <span className="text-2xl">🎓</span>
          <div>
            <p className="font-semibold text-gray-800">Mentra</p>
            <p className="text-xs text-gray-500">Parent Portal</p>
          </div>
        </div>
        <button onClick={logout} className="text-sm text-gray-500 hover:text-red-500">
          Logout
        </button>
      </div>

      <main className="px-10 py-8">
        <h1 className="text-3xl font-semibold mb-6">Parent Dashboard</h1>

        {/* Student Info Card */}
        <div className="bg-white rounded-2xl p-6 mb-6 flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold">{child?.student_name || "Loading..."}</h2>
            <p className="text-sm text-gray-500">
              Class {child?.class} - {child?.section} | Roll No {child?.roll_no}
            </p>
            <p className="text-sm mt-1">
              Mentor: <span className="font-medium">{child?.mentor_name || "Not assigned"}</span>
            </p>
          </div>
          <button
            onClick={downloadReport}
            className="bg-primary text-white px-5 py-2 rounded-xl flex items-center gap-2"
          >
            📄 Download Report
          </button>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <Stat label="Attendance"        value={`${attendancePct}%`} color={attendancePct < 75 ? "text-red-600" : "text-green-600"} />
          <Stat label="Average Marks"     value={`${avgMarks}%`} />
          <Stat label="Backlogs"          value={child?.backlog ?? 0} color={child?.backlog > 0 ? "text-red-600" : "text-green-600"} />
          <Stat label="Upcoming Meetings" value={upcomingMeetings} />
        </div>

        {/* Tabs */}
        <div className="flex gap-6 border-b mb-6">
          {["overview", "marks", "attendance", "feedback", "communication"].map(t => (
            <Tab
              key={t}
              label={t.charAt(0).toUpperCase() + t.slice(1)}
              active={activeTab === t}
              onClick={() => setActiveTab(t)}
            />
          ))}
        </div>

        {/* ── Overview ── */}
        {activeTab === "overview" && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card title="Performance Overview">
              <Progress label={`Attendance (${presentDays}/${totalDays} days)`} value={attendancePct} color={attendancePct < 75 ? "bg-red-500" : "bg-green-500"} />
              <Progress label="Average Marks" value={avgMarks} color="bg-blue-500" />
              {attendancePct < 75 && (
                <div className="mt-3 bg-red-50 border border-red-200 rounded-lg p-3 text-sm text-red-600">
                  ⚠️ Attendance is below 75%. Please ensure regular attendance.
                </div>
              )}
            </Card>

            <Card title="Upcoming Meetings">
              {meetings.filter(m => m.status === "Scheduled").length === 0 && (
                <p className="text-sm text-gray-500">No upcoming meetings</p>
              )}
              {meetings.filter(m => m.status === "Scheduled").map((m, i) => (
                <div key={i} className="bg-blue-50 rounded-xl p-4 mb-3">
                  <p className="font-medium">{m.topic}</p>
                  <p className="text-sm text-gray-600">{m.date} at {m.time}</p>
                  <span className="text-xs bg-blue-200 px-2 py-1 rounded">{m.status}</span>
                </div>
              ))}
            </Card>
          </div>
        )}

        {/* ── Marks ── */}
        {activeTab === "marks" && (
          <Card title="Marks Details">
            {marks.length === 0 && <p className="text-sm text-gray-500">No marks entered yet</p>}
            <table className="w-full text-sm">
              <thead className="border-b text-gray-500">
                <tr>
                  <th className="text-left py-2">Subject</th>
                  <th>Exam Type</th>
                  <th>Marks</th>
                  <th>Max</th>
                  <th>Percentage</th>
                </tr>
              </thead>
              <tbody>
                {marks.map((m, i) => (
                  <tr key={i} className="border-b">
                    <td className="py-3">{m.subject}</td>
                    <td className="text-center">{m.exam_type}</td>
                    <td className="text-center">{m.marks}</td>
                    <td className="text-center">{m.max_marks}</td>
                    <td className={`text-center font-medium ${(m.marks / m.max_marks) * 100 < 40 ? "text-red-600" : "text-green-600"}`}>
                      {((m.marks / m.max_marks) * 100).toFixed(1)}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        )}

        {/* ── Attendance ── */}
        {activeTab === "attendance" && (
          <Card title="Attendance Details">
            <Progress label={`Overall (${presentDays}/${totalDays} days)`} value={attendancePct} color={attendancePct < 75 ? "bg-red-500" : "bg-green-500"} />
            <div className="mt-4 max-h-72 overflow-y-auto">
              <table className="w-full text-sm">
                <thead className="border-b text-gray-500 sticky top-0 bg-white">
                  <tr>
                    <th className="text-left py-2">Date</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {attendance.map((a, i) => (
                    <tr key={i} className="border-b">
                      <td className="py-2">{a.date}</td>
                      <td className={`text-center font-medium ${a.status === "Present" ? "text-green-600" : "text-red-600"}`}>
                        {a.status}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        )}

        {/* ── Feedback ── */}
        {activeTab === "feedback" && (
          <Card title="Feedback from Mentor & Teachers">
            {feedbacks.length === 0 && <p className="text-sm text-gray-500">No feedback yet</p>}
            <div className="space-y-3">
              {feedbacks.map((f, i) => (
                <div key={i} className="bg-gray-50 rounded-xl p-4 border">
                  <div className="flex justify-between items-center mb-1">
                    <span className={`text-xs font-medium px-2 py-1 rounded-full ${
                      f.from_role === "Mentor" ? "bg-purple-100 text-purple-600" : "bg-blue-100 text-blue-600"
                    }`}>
                      {f.from_role}
                    </span>
                    <span className="text-xs text-gray-400">{f.created_at?.slice(0, 10)}</span>
                  </div>
                  <p className="text-sm text-gray-700 mt-1">{f.message}</p>
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* ── Communication ── */}
        {activeTab === "communication" && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Mentor Contact */}
            <Card title="Mentor Contact">
              {child?.mentor_name ? (
                <>
                  <p className="font-medium">{child.mentor_name}</p>
                  <p className="text-sm text-gray-500">{child.mentor_email}</p>
                  {child.mentor_phone && (
                    <p className="text-sm text-gray-500">📞 {child.mentor_phone}</p>
                  )}
                </>
              ) : (
                <p className="text-sm text-gray-500">No mentor assigned yet</p>
              )}
            </Card>

            {/* Teachers Contact */}
            <Card title="Subject Teachers">
              {teachers.length === 0 && <p className="text-sm text-gray-500">No teachers found</p>}
              <div className="space-y-3">
                {teachers.map((t, i) => (
                  <div key={i} className="border rounded-xl p-3">
                    <p className="font-medium text-sm">{t.teacher_name}</p>
                    <p className="text-xs text-gray-500">{t.subject}</p>
                    <p className="text-xs text-gray-500">{t.teacher_email}</p>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        )}
      </main>
    </div>
  );
}

/* ─── Small Components ─────────────────────────────────────────────────────── */

function Tab({ label, active, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`pb-3 font-medium transition ${
        active ? "border-b-2 border-primary text-primary" : "text-gray-500 hover:text-primary"
      }`}
    >
      {label}
    </button>
  );
}

function Stat({ label, value, color = "text-gray-800" }) {
  return (
    <div className="bg-white rounded-2xl p-6">
      <p className="text-sm text-gray-500">{label}</p>
      <p className={`text-2xl font-semibold mt-2 ${color}`}>{value}</p>
    </div>
  );
}

function Card({ title, children }) {
  return (
    <div className="bg-white rounded-2xl p-6 border">
      <h3 className="font-semibold mb-4">{title}</h3>
      {children}
    </div>
  );
}

function Progress({ label, value, color = "bg-green-500" }) {
  return (
    <div className="mb-4">
      <div className="flex justify-between text-sm mb-1">
        <span>{label}</span>
        <span className="font-medium">{value}%</span>
      </div>
      <div className="h-2 bg-gray-200 rounded">
        <div className={`h-2 rounded ${color}`} style={{ width: `${Math.min(value, 100)}%` }} />
      </div>
    </div>
  );
}